# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: update ticker

on: 
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]
  
  workflow_dispatch:
  
#  schedule:
  # every 7:00(UTC) = 16:00(JST)
#  - cron:  '00 07 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
#       fail-fast: false
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip' # caching pip dependencies
    - name: git config
      run: |
        git config user.name "ywakida"
        git config user.email "y.wakida.business@gmai.com"
        git config core.filemode false # ignore file permission
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yfinance pandas_datareader xlrd
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: ticker update
      run: |
        # update ticker list
        python ticker.py
        if ! git diff --exit-code --quiet
        then
          git add *.csv
          git commit -m "update ticker list" -a
          git pull
          git config pull.rebase false
          git push origin main
        fi
        
    - name: chart days update
      run: |
        python chart_days.py
        if ! git diff --exit-code --quiet
        then
          git add *.csv
          git commit -m "update & add chart csv" -a
          git pull
          git config pull.rebase false
          git push origin main
        fi
        
    - name: chart minutes update
      run: |
        python chart_minutes.py
        if ! git diff --exit-code --quiet
        then
          git add *.csv
          git commit -m "update & add chart csv" -a
          git pull
          git config pull.rebase false
          git push origin main
        fi
