# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pickup2

on: 
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]
  
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip' # caching pip dependencies
    - name: git config
      run: |
        git config --global user.name "ywakida"
        git config --global user.email "y.wakida.business@gmai.com"
        git config --global core.filemode false # ignore file permission
        git config --global pull.rebase true # true:rebase false:merge
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yfinance pandas_datareader xlrd plotly
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                
    - name: chart analyze
      run: |
        python -B -c "import todayspickup; todayspickup.create_tickers2()"
        #python -B -c "import todayspickup; todayspickup.change_view()"

    - name: git update
      run: |
        # git update
        git add -A #.csv
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
            echo "there are changes";
            git commit -m "update & add ohlcv csv" -a       
            git pull
            git push origin main
        else
            echo "no changes";
        fi
        
