# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ohlc_day2

on: 
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]
  
  workflow_dispatch:
  
  schedule:
  # every 8:00(UTC) = 17:00(JST) 平日のみ
  - cron:  '00 08 * * 1-5'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip' # caching pip dependencies
    - name: git config
      run: |
        git config --global user.name "ywakida"
        git config --global user.email "y.wakida.business@gmai.com"
        git config --global core.filemode false # ignore file permission
        git config --global pull.rebase true # true:rebase false:merge
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yfinance pandas_datareader xlrd
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                
    - name: ohlc update
      run: |
        python -B -c "import chart_days; chart_days.task2()"
        
    - name: git update
      run: |
        #git add *.csv
        git add -A
        git commit -m "update & add chart csv" -a       
        git pull
        git push origin main
        
