# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ticker

on: 
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]
  
  workflow_dispatch:
  
  schedule:
  # every 10:00(UTC) = 19:00(JST) 平日のみ
  - cron:  '00 10 * * 1-5'
  # every saturday 3:00(UTC) = 12:00(JST)
  #- cron:  '0 3 * * 6'
jobs:
  csv_update:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }} # ブランチ名
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yfinance pandas_datareader xlrd
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: git config
      run: |
        git config --global user.name "ywakida"
        git config --global user.email "y.wakida.business@gmai.com"
        git config --global core.filemode false # ignore file permission
        git config --global pull.rebase true
    - name: ticker update
      run: |
        # update ticker list
        # python ticker.py
        python -B -c "import ticker; ticker.update_list()"

    - name: git update
      run: |
        if ! git diff --exit-code --quiet
        then
          git add *.csv
          git commit -m "update ticker list" -a
          git pull
          git push origin main
        fi
