# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on: 
#  push:
#    branches: [ "main" ]
    
#  pull_request:
#    branches: [ "main" ]
  
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
#       fail-fast: false
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yfinance pandas_datareader xlrd
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: ticker update
      run: |
        # update ticker list
        python ticker.py
        echo "config"
        git config user.name "ywakida"
        git config user.email "y.wakida.business@gmai.com"
        echo "add"
        git add -u
        echo "commit"
        git commit -m "update ticker list" -a
        echo "pull"
        git pull
        echo "push"
        git push origin master
        
    - name: chart update
      run: |
        python chart.py
        git config user.name "ywakida"
        git config user.email "y.wakida.business@gmai.com"
        git add *.csv
        git commit -m "add chart csv" -a
        git pull
        git push origin main
        
        
